#!/usr/bin/env bash

export XAUTHORITY=/home/pa1/.Xauthority
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

/usr/bin/notify-send -i /usr/share/icons/Papirus-Dark/48x48/status/battery-good.svg 'Power Management' '\n\nDischarging'
