#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="/usr/bin/eww"

## Open widgets 
run_eww() {

	## Run eww daemon if not running already
	if [[ ! `pidof eww` ]]; then
		${EWW} daemon &
		sleep 1
	fi

	${EWW} open-many \
		  background \
		  profile \
		  system \
		  clock \
		  uptime \
		  music \
		  github \
		  reddit \
		  twitter \
		  youtube \
		  weather \
		  apps \
		  pacman \
		  logout \
		  sleep \
		  reboot \
		  poweroff \
		  folders &
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    echo "󰍜"
else
    echo "󰅖"
fi

if [[ $1 == "toggle" ]]; then
	if [[ ! -f "$FILE" ]]; then
		touch "$FILE"
		run_eww
	else
		${EWW} close-all
		rm "$FILE"
	fi
fi